spring:
  application:
    name: user-service
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
  datasource:
    url: jdbc:postgresql://db:5432/user_db
    driver-class-name: org.postgresql.Driver
    username: robot
    password: robotpass


server:
    port : 9998
